import type { Game } from "@features/games/lib/types";

/**
 * DATOS MOCK: los 18 juegos del diseño.
 *
 * Sólo los usa `mock-game-repository.ts`. Cuando los juegos vivan en la base de datos,
 * borra este archivo, `mock-game-repository.ts` y `public/mock/` (ver docs/data-sources.md).
 * Las imágenes son las de referencia del diseño y deben reemplazarse por el arte de cada equipo.
 */
export const MOCK_GAMES: readonly Game[] = [
  {
    slug: "ceniza-protocol",
    name: "Ceniza Protocol",
    genre: "Acción",
    team: "Equipo Grava",
    members: 5,
    stand: "A1",
    hasTournament: true,
    description: "Shooter de extracción en una ciudad sepultada por ceniza volcánica.",
    image: { src: "/mock/games/ceniza-protocol.jpg", position: "70% 30%" },
    art: { seed: 0, palette: ["acid", "black"] },
  },
  {
    slug: "los-ultimos-faros",
    name: "Los Últimos Faros",
    genre: "Aventura",
    team: "Equipo Marea",
    members: 4,
    stand: "A2",
    hasTournament: false,
    description:
      "Mantén encendido el último faro del Caribe mientras la marea cambia la isla cada noche.",
    image: { src: "/mock/games/los-ultimos-faros.jpg", position: "50% 30%" },
    art: { seed: 1, palette: ["white", "panel"] },
  },
  {
    slug: "hormigon",
    name: "Hormigón",
    genre: "Puzle",
    team: "Equipo Ocho",
    members: 3,
    stand: "A3",
    hasTournament: false,
    description: "Vierte, fragua y apila concreto para construir torres imposibles.",
    image: { src: "/mock/games/hormigon.jpg", position: "60% 40%" },
    art: { seed: 2, palette: ["black", "light"] },
  },
  {
    slug: "ruta-9",
    name: "Ruta 9",
    genre: "Carreras",
    team: "Equipo Ruido",
    members: 4,
    stand: "A4",
    hasTournament: true,
    description: "Carreras arcade nocturnas sobre periféricos que nunca terminan.",
    image: { src: "/mock/games/ruta-9.jpg", position: "60% 35%" },
    art: { seed: 3, palette: ["acid", "panel"] },
  },
  {
    slug: "subsuelo",
    name: "Subsuelo",
    genre: "Roguelike",
    team: "Equipo Fosa",
    members: 5,
    stand: "B1",
    hasTournament: false,
    description: "Desciende por cenotes y galerías que cambian en cada partida.",
    image: null,
    art: { seed: 4, palette: ["acid", "black"] },
  },
  {
    slug: "kaiju-mercado",
    name: "Kaiju Mercado",
    genre: "Simulación",
    team: "Equipo Tianguis",
    members: 4,
    stand: "B2",
    hasTournament: false,
    description: "Administra un tianguis donde los clientes miden treinta metros.",
    image: null,
    art: { seed: 5, palette: ["black", "acid"] },
  },
  {
    slug: "eco-nulo",
    name: "Eco/Nulo",
    genre: "Ritmo",
    team: "Equipo Señal",
    members: 3,
    stand: "B3",
    hasTournament: true,
    description: "Cada golpe en el ritmo borra una frecuencia del mapa.",
    image: null,
    art: { seed: 6, palette: ["white", "black"] },
  },
  {
    slug: "templo-404",
    name: "Templo 404",
    genre: "Metroidvania",
    team: "Equipo Basalto",
    members: 5,
    stand: "B4",
    hasTournament: false,
    description: "Explora un templo que se corrompe como un archivo dañado.",
    image: null,
    art: { seed: 7, palette: ["acid", "panel"] },
  },
  {
    slug: "marea-roja",
    name: "Marea Roja",
    genre: "Estrategia",
    team: "Equipo Coral",
    members: 4,
    stand: "A5",
    hasTournament: false,
    description: "Defiende el arrecife de una marea tóxica colocando torres de coral.",
    image: null,
    art: { seed: 8, palette: ["acid", "panel"] },
  },
  {
    slug: "neon-taqueria",
    name: "Neón Taquería",
    genre: "Arcade",
    team: "Equipo Comal",
    members: 3,
    stand: "A6",
    hasTournament: false,
    description: "Atiende pedidos imposibles en una taquería que nunca cierra.",
    image: null,
    art: { seed: 9, palette: ["white", "black"] },
  },
  {
    slug: "pulso-cero",
    name: "Pulso Cero",
    genre: "Ritmo",
    team: "Equipo Bajo",
    members: 4,
    stand: "A7",
    hasTournament: false,
    description: "Sincroniza tus saltos con el bajo para cruzar una ciudad apagada.",
    image: null,
    art: { seed: 10, palette: ["acid", "black"] },
  },
  {
    slug: "xibalba-run",
    name: "Xibalbá Run",
    genre: "Plataformas",
    team: "Equipo Ceiba",
    members: 5,
    stand: "A8",
    hasTournament: true,
    description: "Corre por el inframundo maya antes de que se cierre la última puerta.",
    image: null,
    art: { seed: 11, palette: ["black", "acid"] },
  },
  {
    slug: "turbina",
    name: "Turbina",
    genre: "Carreras",
    team: "Equipo Pistón",
    members: 4,
    stand: "A9",
    hasTournament: true,
    description: "Carreras de drones caseros por los techos de Cancún.",
    image: null,
    art: { seed: 12, palette: ["white", "panel"] },
  },
  {
    slug: "sombra-jade",
    name: "Sombra Jade",
    genre: "Sigilo",
    team: "Equipo Jade",
    members: 3,
    stand: "B5",
    hasTournament: false,
    description: "Infíltrate en un museo para recuperar una máscara robada.",
    image: null,
    art: { seed: 13, palette: ["acid", "panel"] },
  },
  {
    slug: "granja-orbital",
    name: "Granja Orbital",
    genre: "Simulación",
    team: "Equipo Nopal",
    members: 4,
    stand: "B6",
    hasTournament: false,
    description: "Cultiva nopales en gravedad cero y abastece una estación espacial.",
    image: null,
    art: { seed: 14, palette: ["black", "light"] },
  },
  {
    slug: "lucha-pixel",
    name: "Lucha Pixel",
    genre: "Pelea",
    team: "Equipo Máscara",
    members: 5,
    stand: "B7",
    hasTournament: true,
    description: "Lucha libre en 2D con llaves que se arman como combos.",
    image: null,
    art: { seed: 15, palette: ["white", "black"] },
  },
  {
    slug: "cenote",
    name: "Cenote",
    genre: "Aventura",
    team: "Equipo Raíz",
    members: 3,
    stand: "B8",
    hasTournament: false,
    description: "Explora cenotes inundados y descubre lo que guardan sus paredes.",
    image: null,
    art: { seed: 16, palette: ["acid", "black"] },
  },
  {
    slug: "circuito-7",
    name: "Circuito 7",
    genre: "Puzle",
    team: "Equipo Voltio",
    members: 4,
    stand: "B9",
    hasTournament: false,
    description: "Conecta circuitos antes de que se acabe la batería del robot.",
    image: null,
    art: { seed: 17, palette: ["acid", "panel"] },
  },
];
